auth_enabled: true
server:
  http_listen_port: 3100
common:
  path_prefix: /var/loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore: { store: inmemory }
schema_config:
  configs:
    - from: 2026-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index: { prefix: index_, period: 24h }
storage_config:
  aws:
    endpoint: objects:8333
    bucketnames: automate-logs
    access_key_id: ${OBJECT_STORAGE_ACCESS_KEY}
    secret_access_key: ${OBJECT_STORAGE_SECRET_KEY}
    insecure: true
    s3forcepathstyle: true
  tsdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
ingester:
  wal: { enabled: true, dir: /var/loki/wal }
compactor:
  working_directory: /var/loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_store: s3
limits_config:
  retention_period: 720h
  allow_structured_metadata: true
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  ingestion_rate_mb: 1
  ingestion_burst_size_mb: 4
  max_query_length: 720h
  split_queries_by_interval: 24h
  max_query_parallelism: 4
  max_entries_limit_per_query: 2001
  max_global_streams_per_user: 128
querier:
  max_concurrent: 4
