namespace Infrastructure.Observability;

/// <summary>Reviewed source literals; new templates/categories require explicit review before platform export.</summary>
internal static class PlatformLogCatalog
{
    /// <summary>Fixed application messages; interpolated and unknown provider templates are excluded.</summary>
    internal static readonly HashSet<string> Templates = new(StringComparer.Ordinal)
    {
        "Outbound HTTP request started: method {HttpMethod}.",
        "Outbound HTTP request sent: method {HttpMethod}.",
        "Outbound HTTP response received: status {StatusCode}, duration {ElapsedMilliseconds} ms.",
        "Outbound HTTP request completed: status {StatusCode}, duration {ElapsedMilliseconds} ms.",
        "Authentication scheme {AuthenticationScheme} signed in.",
        "Authentication scheme {AuthenticationScheme} signed out.",
        "Authentication scheme {AuthenticationScheme} challenged.",
        "Authentication scheme {AuthenticationScheme} forbidden.",
        "Authentication scheme {AuthenticationScheme} authenticated.",
        "Database migrations are current.",
        "Module event {EventCode}; additional text fields withheld.",
        "Module event {EventCode} failed: {FailureType}; additional text fields withheld.",
        "Request started: method {HttpMethod}, area {RequestArea}, request {RequestId}.",
        "Request finished: method {HttpMethod}, area {RequestArea}, request {RequestId}, status {StatusCode}, duration {DurationMs} ms, authentication {AuthenticationState}, user {UserId}.",
        "Request failed: request {RequestId}, duration {DurationMs} ms, failure {FailureType}.",
        "Login attempt started.",
        "Queued {JobType} for project {ProjectId}.",
        "Deployment status persisted for project {ProjectId}, deployment {DeploymentId}: {Status}.",
        "Local project configuration saved for project {ProjectId}, user {UserId}.",
        "GitHub project saved for project {ProjectId}, user {UserId}.",
        "Diagnostic egress consent changed for project {ProjectId}, user {UserId}: {ConsentState}.",
        "Diagnostic egress consent change denied for project {ProjectId}, user {UserId}.",
        "User registration completed for user {UserId}.",
        "Email verification completed for user {UserId}.",
        "Azure account connection saved for user {UserId}.",
        "GitHub account profile saved for user {UserId}.",
        "Deployment artifact saved: {OutputFile}.",
        "Login completed for user {UserId}.",
        "Logout completed for user {UserId}.",
        "An error occurred during email verification.",
        "Daily telemetry aggregation delayed: {FailureType}.",
        "Daily telemetry unavailable for deployment {DeploymentId}: {FailureType}.",
        "Disk telemetry delivery delayed: {FailureType}.",
        "Discarded an incomplete unacknowledged telemetry segment.",
        "Analysis retention cleanup failed: {FailureType}.",
        "AutoMate operation {Operation} outcome {Outcome}.",
        "Azure Container Apps runtime monitoring coordinator started.",
        "Azure Container Apps runtime monitoring coordinator stopped.",
        "Azure OIDC trust configured.",
        "Azure federated credential readiness check timed out after {AttemptCount} attempts; continuing while Azure propagates the credential.",
        "Azure federated credential was not readable on attempt {Attempt}: {FailureType}.",
        "Azure runtime monitoring failed for deployment {DeploymentId}. Failure {FailureType}.",
        "Azure runtime monitoring was not registered for deployment {DeploymentId}: incomplete configuration.",
        "Azure runtime streaming could not start for deployment {DeploymentId} ({FailureType}).",
        "Building Docker image.",
        "Cloud deployment diagnostic delivery failed for project {ProjectId} ({FailureType}).",
        "Cloud deployment files committed.",
        "Cloud deployment preparation failed: {FailureType}.",
        "Cloud launch {RunId} attempt {Attempt} failed ({FailureType}).",
        "Cloud launch {RunId} stopped unexpectedly; its lease will recover. Failure {FailureType}.",
        "Cloud runtime recovery requires Azure reconnection for deployment {DeploymentId}.",
        "Cloud workflow monitor will retry after a bounded delay. Failure {FailureType}.",
        "Committed {FileCount} cloud deployment files to GitHub.",
        "Compose outcome diagnostic unavailable: {FailureType}.",
        "Compose output diagnostic unavailable: {FailureType}.",
        "Compose output reader ended: {FailureType}.",
        "Docker Compose process exited for project {ProjectId} with code {Code}.",
        "Docker Compose command outcome for project {ProjectId}: {ComposeOutcome}.",
        "Database dependency detected for project {ProjectId}: {DbType}.",
        "Finished {JobType} for project {ProjectId} with outcome {Outcome}.",
        "Local diagnostic cleanup completed for project {ProjectId}.",
        "Application started.",
        "Application is shutting down.",
        "Hosting environment initialized.",
        "Content root initialized.",
        "HTTP listener started.",
        "Could not deliver diagnostic availability notice. Failure {FailureType}.",
        "Could not persist theme preference.",
        "Could not publish cloud failure for deployment {DeploymentId}: {FailureType}.",
        "Could not read theme preference from local storage.",
        "Daily telemetry aggregation delayed: {FailureType}.",
        "Daily telemetry unavailable for deployment {DeploymentId}: {FailureType}.",
        "Deployment analysis worker is stopping.",
        "Deployment analysis worker recovered: {FailureType}.",
        "Deployment cleanup and synchronization failed: {FailureType}.",
        "Deployment diagnostic dispatcher started.",
        "Deployment diagnostic dispatcher stopped.",
        "Deployment finished successfully.",
        "Deployment job scheduler stopped unexpectedly: {FailureType}.",
        "Deployment job worker stopped.",
        "Deployment job {JobType} failed for project {ProjectId}: {FailureType}.",
        "Deployment job {JobType} was cancelled for project {ProjectId}.",
        "Deployment lifecycle collection unavailable: {FailureType}.",
        "Deployment status subscriber failed for project {ProjectId} with status {Status}: {FailureType}.",
        "DeploymentCleanupHostedService is stopping.",
        "Discarded an incomplete unacknowledged telemetry segment.",
        "Disk telemetry delivery delayed: {FailureType}.",
        "Docker Compose command unavailable: {FailureType}.",
        "Docker Compose listing unavailable: {FailureType}.",
        "Docker collector unavailable. Source {Source} failure {FailureType}.",
        "Docker container start canceled: {FailureType}.",
        "Docker container start unavailable: {FailureType}.",
        "Docker container started successfully.",
        "Docker container was created but failed to start.",
        "Docker daemon ping unavailable: {FailureType}.",
        "Docker host port lookup canceled: {FailureType}.",
        "Docker host port lookup unavailable: {FailureType}.",
        "Docker image build canceled: {FailureType}.",
        "Docker image build unavailable: {FailureType}.",
        "Docker image built successfully.",
        "Docker lifecycle startup is delayed; timestamp recovery remains active.",
        "Docker metric stream ended after unexpected provider cancellation.",
        "Docker metric stream stopped after cancellation.",
        "Docker metric subscription unavailable: {FailureType}.",
        "Docker replay checkpoint unavailable: {FailureType}.",
        "Docker status check failed.",
        "Docker subscription ended during cancellation.",
        "Docker subscription ended: {FailureType}.",
        "Dropped deployment diagnostic because the bounded delivery queue is full. Source {Source} kind {Kind} project {ProjectId}.",
        "Durable diagnostic live delivery unavailable: {FailureType}.",
        "Durable diagnostic storage unavailable. Source {Source} failure {FailureType}.",
        "Expired SaaS cloud control metadata cleanup failed. Failure {FailureType}.",
        "Expired deployment diagnostic cleanup failed. Failure {FailureType}.",
        "Expired {Count} buffered telemetry events for {TenantId}; history is incomplete.",
        "Failed to deliver deployment diagnostic. Source {Source} kind {Kind} failure {FailureType}.",
        "Failed to load GitHub repositories.",
        "Failed to persist deployment diagnostic. Source {Source} kind {Kind} failure {FailureType}.",
        "Failed to publish deployment failure for project {ProjectId}: {FailureType}.",
        "Failed to queue cloud deployment for project {ProjectId} Failure {FailureType}.",
        "Failed to queue deployment for project {ProjectId} Failure {FailureType}.",
        "Failed to queue stop deployment for project {ProjectId} Failure {FailureType}.",
        "Failed to save GitHub repository {RepositoryUrl}.",
        "Failed to save local project {ProjectPath}.",
        "Failed to scan local repositories at {SearchPath}.",
        "Failed to start SignalR connection for project {ProjectId} Failure {FailureType}.",
        "GitHub API network request failed: {FailureType}.",
        "GitHub cloud deployment commit failed: {FailureType}.",
        "GitHub cloud deployment commit was canceled.",
        "GitHub final log reconciliation failed for run {RunId} ({FailureType}); preserving the workflow conclusion.",
        "GitHub repository secret upserted.",
        "GitHub returned {StatusCode} while downloading workflow job logs for job {JobId}.",
        "GitHub workflow diagnostic collection failed for run {RunId} ({FailureType}); workflow result polling continues.",
        "GitHub workflow dispatched.",
        "Lease renewal failed for cloud launch {RunId}; the run will recover. Failure {FailureType}.",
        "Live Docker metric delivery unavailable for project {ProjectId}: {FailureType}.",
        "Local deployment failed: {FailureType}.",
        "Local diagnostics are shutting down.",
        "Local phase diagnostic unavailable: {FailureType}.",
        "Local resource conflict diagnostic unavailable: {FailureType}.",
        "Local runtime collection recovery unavailable: {FailureType}.",
        "Local runtime collection recovery will retry: {FailureType}.",
        "Local subscriptions were canceled.",
        "Local supervision will be restored by recovery: {FailureType}.",
        "Log hub connection could not rejoin the project group for project {ProjectId}. Failure {FailureType}.",
        "Log hub connection is reconnecting for project {ProjectId}. Failure {FailureType}.",
        "Log hub connection rejoined the project group for project {ProjectId}.",
        "Log replay canceled because the project connection closed.",
        "Rate limit rejected request. Authentication state {AuthenticationState}.",
        "Redacted {RedactedValueCount} value(s) from deployment diagnostic. Source {Source} kind {Kind} project {ProjectId}.",
        "Registration failed unexpectedly for email {Email}.",
        "Rejected log hub group join because the secure token was invalid or expired.",
        "Repository cache read canceled: {FailureType}.",
        "Repository cache read unavailable; falling back to API: {FailureType}.",
        "Repository cache write canceled: {FailureType}.",
        "Repository cache write unavailable: {FailureType}.",
        "SaaS cloud admission failed; retrying after a bounded pause. Failure {FailureType}.",
        "SaaS cloud control metrics could not be sampled. Failure {FailureType}.",
        "SaaS cloud status refresh failed for {ProjectId}. Failure {FailureType}.",
        "Saved metric recovery unavailable: {FailureType}.",
        "Skipping log hub connection for project {ProjectId} because no user ID was resolved.",
        "Specialized history unavailable for {DeploymentId}: {FailureType}.",
        "Starting Docker Compose down for project {ProjectId}, deployment {DeploymentId}.",
        "Starting Docker Compose up for project {ProjectId}, deployment {DeploymentId}.",
        "Starting Docker container with port {HostPort} mapped to {ContainerPort}.",
        "Starting Docker metrics for project {ProjectId}, deployment {DeploymentId}.",
        "Starting cloud deployment preparation.",
        "Starting local deployment process.",
        "Starting {JobType} for project {ProjectId} after {WaitMs:F0} ms queued.",
        "Stop lifecycle collection unavailable: {FailureType}.",
        "Telemetry admission dropped an event for owner {TenantId}; history is incomplete.",
        "Telemetry delivery cycle unavailable: {FailureType}.",
        "Telemetry owner {TenantId} delivery delayed by {DelaySeconds}s: {FailureType}.",
        "Telemetry spool cleanup is overdue by {OverdueSeconds}s; operator attention is required.",
        "Temporary Docker build context cleanup failed: {FailureType}.",
        "Terminal catch-up unavailable: {FailureType}.",
        "[ApplicationService] Attempted to add a GitHub project with invalid parameters.",
        "[ApplicationService] Attempted to add a local project with an empty user ID.",
        "[ApplicationService] C# project '{CsProjectName}' already exists in project '{ProjectName}'.",
        "[ApplicationService] Creating new local project '{ProjectName}' for user {UserId}.",
        "[ApplicationService] Database error occurred while adding GitHub project '{AppName}'.",
        "[ApplicationService] Database error occurred while adding local project '{ProjectName}'.",
        "[ApplicationService] Database error occurred while deleting project {AppId}.",
        "[ApplicationService] GitHub project with URL '{GitUrl}' already exists for user {UserId}.",
        "[ApplicationService] Project with ID {AppId} not found or does not belong to user {UserId}.",
        "[ApplicationService] Successfully added C# project '{CsProjectName}' to project '{ProjectName}'.",
        "[ApplicationService] Successfully added GitHub project '{AppName}' for user {UserId}.",
        "[ApplicationService] Successfully deleted project {AppId} for user {UserId}.",
        "[AuthService] Azure account linking failed because current user '{Identifier}' was not found.",
        "[AuthService] Created new GitHub user: {Username}",
        "[AuthService] Email verification failed for token fingerprint '{TokenFingerprint}'.",
        "[AuthService] Email verified successfully for user '{Username}'.",
        "[AuthService] Failed to send verification email.",
        "[AuthService] Linked Azure account '{AzureAccountId}' to user '{UserId}'.",
        "[AuthService] Registration failed because required fields were empty.",
        "[AuthService] Registration failed while saving user '{Username}'.",
        "[AuthService] Registration failed: email is already in use for username '{Username}'.",
        "[AuthService] Successfully registered new user '{Username}'.",
        "[AuthService] Updated existing GitHub user: {Username}",
        "[AuthService] Verification email failed and cleanup failed for user '{UserId}'.",
        "[AzureDeploymentOrchestrator] Azure resource provider {ProviderNamespace} is registered on subscription {SubscriptionId}.",
        "[DOCKER BUILD ERROR]: {ErrorMessage}",
        "[DeploymentCleanupHostedService] Deployment cleanup was cancelled.",
        "[DeploymentCleanupHostedService] Deployment sync completed.",
        "[DeploymentCleanupHostedService] Starting to clean up and sync deployments...",
        "[DeploymentCleanupHostedService] Successfully cleaned up and marked {Count} stuck deployments (Starting) as 'Failed'.",
        "[DeploymentCleanupHostedService] Synchronized {Count} deployments with the actual Docker state.",
        "[DockerService] 'docker compose ls' failed. Exit Code: {Code}, Error: {Error}",
        "[DockerService] 'docker compose ls' operation was cancelled or timed out. Exception: {Exception}",
        "[DockerService] {Message}",
        "[DockerService] {Status}",
        "[DockerService] {Status} {Progress}",
        "[GitHubService] Attempted to get GitHub repositories with an empty access token.",
        "[GitHubService] Fetching repositories from GitHub API was cancelled.",
        "[GitHubService] Fetching repositories from GitHub API...",
        "[GitHubService] GitHub API returned error status code: {StatusCode} for getting repositories.",
        "[GitHubService] Successfully retrieved and cached {Count} repositories from GitHub API.",
        "[GitHubService] Successfully retrieved {Count} GitHub repositories from cache.",
        "[GmailSenderService] Attempting to send email with subject '{Subject}'...",
        "[GmailSenderService] Email sender credentials are not configured.",
        "[GmailSenderService] Email successfully sent.",
        "[LocalDeploymentOrchestrator] Deployment failed: Database record for CsProject {Id} not found.",
        "[LocalDeploymentOrchestrator] Deployment stopped successfully for Project ID {Id}.",
        "[LocalDeploymentOrchestrator] Failed to stop deployment for Project ID {Id}.",
        "[LocalDeploymentOrchestrator] No .automate directory found at {Path}. Cannot stop deployment.",
        "[LocalDeploymentOrchestrator] Step 1/4: Locating solution root.",
        "[LocalDeploymentOrchestrator] Step 2/4: Scanning project content for dependencies...",
        "[LocalDeploymentOrchestrator] Step 3/4: Generating Infrastructure-as-Code files (Dockerfile, docker-compose)...",
        "[LocalDeploymentOrchestrator] Step 4/4: Starting Docker Compose deployment...",
        "[LocalDeploymentOrchestrator] Stopping deployment for Project ID {Id}...",
        "[LocalSystemScannerService] Access denied to directory, skipping: {CurrentPath}.Exception: {Exception}",
        "[LocalSystemScannerService] Access denied while searching for .csproj files: {CurrentPath}. Exception: {Exception}",
        "[LocalSystemScannerService] Could not find a distinct solution root. Falling back to project directory: {FallbackDir}",
        "[LocalSystemScannerService] Error processing git repository at {RepoPath}",
        "[LocalSystemScannerService] Error scanning for .csproj in directory: {CurrentPath}",
        "[LocalSystemScannerService] Failed to parse .csproj file to determine project type: {CsProjPath}",
        "[LocalSystemScannerService] Invalid or non-existent root path provided for scanning: {RootPath}",
        "[LocalSystemScannerService] Parsing cancelled for .csproj file: {CsProjPath}, Exception: {Exception}",
        "[LocalSystemScannerService] Project file not found: {ProjectFilePath}",
        "[LocalSystemScannerService] Scan cancelled for directory: {CurrentPath}, Exception: {Exception}",
        "[LocalSystemScannerService] Scan cancelled for repository: {RepoPath}, Exception: {Exception}",
        "[LocalSystemScannerService] Scan completed. Found {Count} local projects.",
        "[LocalSystemScannerService] Solution root found at: {SolutionRoot}",
        "[LocalSystemScannerService] Starting system scan for .NET projects in: {RootPath}",
        "[LocalSystemScannerService] Unexpected error while scanning directory: {CurrentPath}",
        "[ProjectScannerService] Database dependency detected for project '{ProjectName}': {DbType}",
        "[ProjectScannerService] Database providers JSON file not found at: {DbProvidersJsonPath}",
        "[ProjectScannerService] Dependency analysis cancelled for project '{ProjectName}'.Ex: {ExceptionMessage}",
        "[ProjectScannerService] Environment variable extraction cancelled for project '{ProjectPath}'.Ex: {ExceptionMessage}",
        "[ProjectScannerService] Error extracting environment variables from config files at: {ProjectPath}",
        "[ProjectScannerService] Error parsing launchSettings.json at {LaunchSettingsPath}",
        "[ProjectScannerService] Error scanning .env file: {EnvFilePath}",
        "[ProjectScannerService] Error scanning csproj dependencies for project: {ProjectName}",
        "[ProjectScannerService] Failed to find an available port. Falling back to default port 8080.",
        "[ProjectScannerService] Failed to parse JSON file: {File}",
        "[ProjectScannerService] Failed to parse database-providers.json",
        "[ProjectScannerService] Operation canceled while parsing database-providers.json",
        "[ProjectScannerService] Operation canceled while parsing launchSettings.json",
        "[ProjectScannerService] Operation canceled while scanning .env file: {EnvFilePath}",
        "[ProjectScannerService] Successfully allocated dynamic port: {Port}",
        "[ProjectScannerService] Successfully scanned .env file: {EnvFilePath}",
        "[ProjectScannerService] The project file '{FilePath}' does not exist.",
        "[Startup] Critical database connectivity error during initialization. Failure {FailureType}.",
        "[Startup] Database migrations are current.",
        "[Startup] Initializing infrastructure and checking dependencies...",
        "[TemplateService] Could not parse Scriban template: {TemplateFile}. Errors: {Errors}",
        "[TemplateService] Failed to parse template-manifest.json",
        "[TemplateService] Generated file saved: {OutputPath}",
        "[TemplateService] Successfully rendered: {OutputFile}",
        "[TemplateService] Template generation cancelled for '{OutputFile}'.",
        "[TemplateService] Template manifest is empty or could not be loaded. No templates will be generated.",
        "[TemplateService] Template manifest loading cancelled. Exception: {Exception}",
        "[TemplateService] Template manifest not found at: {ManifestPath}",
        "[TemplateService] Templates directory not found at: {TemplatesDirectory}",
        "[TemplateService] The template file '{TemplateFile}' does not exist!",
        "[TemplateService] Unexpected error occurred while generating template: {TemplateFile}",
        "[{LogSource}] Failed to update deployment status {Status} for Deployment ID {Id}. Failure {FailureType}."
    };

    /// <summary>Known application and framework logger categories; unknown names use a fixed fallback.</summary>
    internal static readonly HashSet<string> Categories = new(StringComparer.Ordinal)
    {
        "AppStartup",
        "Application.Orchestration.DeploymentJobQueue",
        "Web.Observability.RequestAuditMiddleware",
        "Web.Routes.Endpoints.Auth.LogoutEndpoint",
        "Microsoft.EntityFrameworkCore.Migrations",
        "Microsoft.EntityFrameworkCore.Infrastructure",
        "Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler",
        "Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler",
        "AspNet.Security.OAuth.GitHub.GitHubHandler",
        "Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager",
        "Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher",
        "Microsoft.AspNetCore.SignalR.HubConnectionHandler",
        "Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher",
        "Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost",
        "Microsoft.AspNetCore.Components.Server.Circuits.CircuitRegistry",
        "AppConfiguration",
        "Application.Auth.AuthService",
        "Application.Data.Apps.ApplicationService",
        "Application.Orchestration.CloudDeploymentOrchestrator",
        "Application.Orchestration.DeploymentCleanupHostedService",
        "Application.Orchestration.DeploymentJobWorker",
        "Application.Orchestration.DeploymentStatusNotifier",
        "Application.Orchestration.DeploymentStatusUpdater",
        "Application.Orchestration.GitHubWorkflowMonitor",
        "Application.Orchestration.LocalDeploymentLogStreamManager",
        "Application.Orchestration.LocalDeploymentOrchestrator",
        "Application.Orchestration.LocalHostPortAvailability",
        "Application.Orchestration.LocalRuntimeRecoveryService",
        "Application.Orchestration.TargetState",
        "ApplicationService",
        "AuthService",
        "AutoMate.Platform",
        "AutoMate.Security.Authentication",
        "AutoMate.Security.RateLimiting",
        "Web.Configs.SecurityAuditResultHandler",
        "Web.Routes.Endpoints.Auth.LoginEndpoint",
        "AzureContainerAppRuntimeStreamer",
        "AzureDeploymentOrchestrator",
        "AzureFederatedCredentialService",
        "AzureResourceProviderRegistrar",
        "CloudDeploymentOrchestrator",
        "CloudDeploymentScheduler",
        "CloudRunMetricsService",
        "CloudRunMonitor",
        "CloudRunMonitorService",
        "CloudRunProcessor",
        "CloudRunRetentionService",
        "ContainerAppStreamTarget",
        "DaemonProgress",
        "DatabaseProviderRuleCatalog",
        "DeploymentAnalysisRetentionService",
        "DeploymentAnalysisWorker",
        "DeploymentAnalysisService",
        "FailedDeploymentAnalysisDispatcher",
        "DeploymentCleanupHostedService",
        "DeploymentDiagnosticDispatcher",
        "DeploymentDiagnosticPublisher",
        "DeploymentDiagnosticRetentionService",
        "DeploymentJobWorker",
        "DeploymentStatusNotifier",
        "DeploymentStatusUpdater",
        "DeploymentTelemetryStore",
        "DiskSpoolOptions",
        "DiskTelemetryDeliveryWorker",
        "DiskTelemetrySpool",
        "DockerBuildContextArchive",
        "DockerBuildProgress",
        "DockerCli",
        "DockerDiagnosticCollector",
        "DockerMetricDelivery",
        "DockerService",
        "GitHubRepos",
        "GitHubRepositoryCache",
        "GitHubService",
        "GitHubWorkflowMonitor",
        "GmailSenderService",
        "Infrastructure.Ai.DeploymentAnalysisRetentionService",
        "Infrastructure.Ai.DeploymentAnalysisWorker",
        "Infrastructure.Ai.DeploymentAnalysisService",
        "Infrastructure.Ai.FailedDeploymentAnalysisDispatcher",
        "Infrastructure.ApplicationServices.Orchestration.CloudDeploymentScheduler",
        "Infrastructure.ApplicationServices.Orchestration.CloudRunMetricsService",
        "Infrastructure.ApplicationServices.Orchestration.CloudRunMonitor",
        "Infrastructure.ApplicationServices.Orchestration.CloudRunMonitorService",
        "Infrastructure.ApplicationServices.Orchestration.CloudRunProcessor",
        "Infrastructure.ApplicationServices.Orchestration.CloudRunRetentionService",
        "Infrastructure.Azure.AzureContainerAppRuntimeStreamer",
        "Infrastructure.Azure.AzureDeploymentOrchestrator",
        "Infrastructure.Azure.AzureFederatedCredentialService",
        "Infrastructure.Azure.AzureResourceProviderRegistrar",
        "Infrastructure.Azure.ContainerAppStreamTarget",
        "Infrastructure.Diagnostics.DeploymentDiagnosticDispatcher",
        "Infrastructure.Diagnostics.DeploymentDiagnosticPublisher",
        "Infrastructure.Diagnostics.DeploymentDiagnosticRetentionService",
        "Infrastructure.Diagnostics.DeploymentTelemetryStore",
        "Infrastructure.Diagnostics.DiskSpoolOptions",
        "Infrastructure.Diagnostics.DiskTelemetryDeliveryWorker",
        "Infrastructure.Diagnostics.DiskTelemetrySpool",
        "Infrastructure.Diagnostics.DiskTelemetryDeliveryWorker",
        "Infrastructure.Diagnostics.TelemetryDailyAggregationWorker",
        "Infrastructure.Diagnostics.TelemetryDeliveryWorker",
        "Infrastructure.Diagnostics.TelemetryTags",
        "Infrastructure.Docker.DaemonProgress",
        "Infrastructure.Docker.DockerBuildContextArchive",
        "Infrastructure.Docker.DockerBuildProgress",
        "Infrastructure.Docker.DockerCli",
        "Infrastructure.Docker.DockerDiagnosticCollector",
        "Infrastructure.Docker.DockerMetricDelivery",
        "Infrastructure.Docker.DockerService",
        "Infrastructure.Email.GmailSenderService",
        "Infrastructure.GitHub.GitHubRepositoryCache",
        "Infrastructure.GitHub.GitHubService",
        "Infrastructure.Scanner.DatabaseProviderRuleCatalog",
        "Infrastructure.Scanner.LocalCsProjectParser",
        "Infrastructure.Scanner.LocalSystemScannerService",
        "Infrastructure.Scanner.ProjectEnvironmentVariableExtractor",
        "Infrastructure.Scanner.ProjectScannerService",
        "Infrastructure.Scanner.ScannerPortProvider",
        "Infrastructure.Templating.ScribanTemplateRenderer",
        "Infrastructure.Templating.TemplateFileWriter",
        "Infrastructure.Templating.TemplateManifestCatalog",
        "Infrastructure.Templating.TemplatingService",
        "LocalCsProjectParser",
        "LocalDeploymentLogStreamManager",
        "LocalDeploymentOrchestrator",
        "LocalGitRepos",
        "LocalHostPortAvailability",
        "LocalRuntimeRecoveryService",
        "LocalSystemScannerService",
        "LogHub",
        "MainLayout",
        "Microsoft.AspNetCore.Hosting.Diagnostics",
        "Microsoft.AspNetCore.Routing.EndpointMiddleware",
        "Microsoft.AspNetCore.Server.Kestrel",
        "Microsoft.AspNetCore.Server.Kestrel.Connections",
        "Microsoft.EntityFrameworkCore.Database.Command",
        "Microsoft.EntityFrameworkCore.Update",
        "Microsoft.Hosting.Lifetime",
        "NavMenu",
        "ProjectDetails",
        "ProjectEnvironmentVariableExtractor",
        "ProjectScannerService",
        "RegisterModel",
        "RegistryForm",
        "ScannerPortProvider",
        "ScribanTemplateRenderer",
        "ServiceConfiguration",
        "System.Net.Http.HttpClient.Default.ClientHandler",
        "System.Net.Http.HttpClient.Default.LogicalHandler",
        "System.Net.Http.HttpClient.DeploymentTelemetry.ClientHandler",
        "System.Net.Http.HttpClient.DeploymentTelemetry.LogicalHandler",
        "System.Net.Http.HttpClient.IGitHubAppCredentials.ClientHandler",
        "System.Net.Http.HttpClient.IGitHubAppCredentials.LogicalHandler",
        "System.Net.Http.HttpClient.IGitHubService.ClientHandler",
        "System.Net.Http.HttpClient.IGitHubService.LogicalHandler",
        "System.Net.Http.HttpClient.ILlmAnalysisProvider.ClientHandler",
        "System.Net.Http.HttpClient.ILlmAnalysisProvider.LogicalHandler",
        "TargetState",
        "TelemetryDailyAggregationWorker",
        "TelemetryDeliveryWorker",
        "TelemetryTags",
        "TemplateFileWriter",
        "TemplateManifestCatalog",
        "TemplatingService",
        "VerifyEmail",
        "Web.Components.Layout.MainLayout",
        "Web.Components.Layout.NavMenu",
        "Web.Components.Pages.GitHubRepos",
        "Web.Components.Pages.LocalGitRepos",
        "Web.Components.Pages.ProjectDetails",
        "Web.Components.Pages.Dashboard",
        "Web.Components.Pages.RegisterModel",
        "Web.Components.Pages.RegistryForm",
        "Web.Components.Pages.VerifyEmail",
        "Web.Configs.AppConfiguration",
        "Web.Configs.ServiceConfiguration",
        "Web.Hubs.LogHub"
    };
}