// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Services.Data;

#nullable disable

namespace Services.Migrations
{
    [DbContext(typeof(AutoMateDbContext))]
    [Migration("20260524171414_RefactorRemoteUser")]
    partial class RefactorRemoteUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AppType")
                        .HasColumnType("integer")
                        .HasColumnName("app_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SourcePathOrUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_path_or_url");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_applications_user_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudAzureRegion")
                        .HasColumnType("text")
                        .HasColumnName("cloud_azure_region");

                    b.Property<string>("CloudContainerAppName")
                        .HasColumnType("text")
                        .HasColumnName("cloud_container_app_name");

                    b.Property<string>("CloudRegistryName")
                        .HasColumnType("text")
                        .HasColumnName("cloud_registry_name");

                    b.Property<string>("CloudResourceGroupName")
                        .HasColumnType("text")
                        .HasColumnName("cloud_resource_group_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CsProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("cs_project_id");

                    b.Property<string>("DotNetVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dot_net_version");

                    b.Property<string>("EnvironmentVariablesJson")
                        .HasColumnType("text")
                        .HasColumnName("environment_variables_json");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<int?>("LocalExposedPort")
                        .HasColumnType("integer")
                        .HasColumnName("local_exposed_port");

                    b.Property<bool>("RequiresDb")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_db");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_configs");

                    b.HasIndex("CsProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_configs_cs_project_id");

                    b.ToTable("app_configs", (string)null);
                });

            modelBuilder.Entity("Core.Entities.CsProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsWebProject")
                        .HasColumnType("boolean")
                        .HasColumnName("is_web_project");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cs_projects");

                    b.HasIndex("AppId")
                        .HasDatabaseName("ix_cs_projects_app_id");

                    b.ToTable("cs_projects", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudAppUrl")
                        .HasColumnType("text")
                        .HasColumnName("cloud_app_url");

                    b.Property<string>("CloudContainerRevision")
                        .HasColumnType("text")
                        .HasColumnName("cloud_container_revision");

                    b.Property<long?>("CloudGitHubActionRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("cloud_git_hub_action_run_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CsProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("cs_project_id");

                    b.Property<string>("DockerContainerId")
                        .HasColumnType("text")
                        .HasColumnName("docker_container_id");

                    b.Property<string>("ImageTag")
                        .HasColumnType("text")
                        .HasColumnName("image_tag");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("CsProjectId")
                        .HasDatabaseName("ix_deployments_cs_project_id");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("user_type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Core.Entities.LocalUser", b =>
                {
                    b.HasBaseType("Core.Entities.User");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("email_verification_token");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("VerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_token_expiry");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator().HasValue("local");
                });

            modelBuilder.Entity("Core.Entities.RemoteUser", b =>
                {
                    b.HasBaseType("Core.Entities.User");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("AzureAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("azure_access_token");

                    b.Property<string>("AzureAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("azure_account_id");

                    b.Property<string>("AzureRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("azure_refresh_token");

                    b.Property<string>("AzureSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("azure_subscription_id");

                    b.Property<string>("AzureTenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("azure_tenant_id");

                    b.Property<DateTimeOffset?>("AzureTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("azure_token_expires_at");

                    b.Property<string>("GitHubAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("git_hub_access_token");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator().HasValue("github");
                });

            modelBuilder.Entity("Core.Entities.Application", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Configuration", b =>
                {
                    b.HasOne("Core.Entities.CsProject", "CsProject")
                        .WithOne("Configuration")
                        .HasForeignKey("Core.Entities.Configuration", "CsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_configs_cs_projects_cs_project_id");

                    b.Navigation("CsProject");
                });

            modelBuilder.Entity("Core.Entities.CsProject", b =>
                {
                    b.HasOne("Core.Entities.Application", "Application")
                        .WithMany("CsProjects")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cs_projects_applications_app_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Core.Entities.Deployment", b =>
                {
                    b.HasOne("Core.Entities.CsProject", "CsProject")
                        .WithMany("Deployments")
                        .HasForeignKey("CsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_cs_projects_cs_project_id");

                    b.Navigation("CsProject");
                });

            modelBuilder.Entity("Core.Entities.Application", b =>
                {
                    b.Navigation("CsProjects");
                });

            modelBuilder.Entity("Core.Entities.CsProject", b =>
                {
                    b.Navigation("Configuration");

                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
