// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AutoMateDbContext))]
    [Migration("20260928212104_AddAzureContainerAppLogCheckpoints")]
    partial class AddAzureContainerAppLogCheckpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AppType")
                        .HasColumnType("integer")
                        .HasColumnName("app_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SourcePathOrUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_path_or_url");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_applications_user_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AzureContainerAppLogCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<DateTimeOffset?>("LastSuccessfulQueryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_query_at");

                    b.Property<string>("LastTieBreaker")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_tie_breaker");

                    b.Property<DateTimeOffset?>("LastTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_timestamp");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_azure_container_app_log_checkpoints");

                    b.HasIndex("DeploymentId", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_azure_container_app_log_checkpoints_deployment_id_source");

                    b.ToTable("azure_container_app_log_checkpoints", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudAzureRegion")
                        .HasColumnType("text")
                        .HasColumnName("cloud_azure_region");

                    b.Property<string>("CloudContainerAppName")
                        .HasColumnType("text")
                        .HasColumnName("cloud_container_app_name");

                    b.Property<string>("CloudRegistryName")
                        .HasColumnType("text")
                        .HasColumnName("cloud_registry_name");

                    b.Property<string>("CloudResourceGroupName")
                        .HasColumnType("text")
                        .HasColumnName("cloud_resource_group_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CsProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("cs_project_id");

                    b.Property<string>("DotNetVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dot_net_version");

                    b.Property<string>("EnvironmentVariablesJson")
                        .HasColumnType("text")
                        .HasColumnName("environment_variables_json");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<int?>("LocalExposedPort")
                        .HasColumnType("integer")
                        .HasColumnName("local_exposed_port");

                    b.Property<bool>("RequiresDb")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_db");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_configs");

                    b.HasIndex("CsProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_configs_cs_project_id");

                    b.ToTable("app_configs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CsProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsWebProject")
                        .HasColumnType("boolean")
                        .HasColumnName("is_web_project");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cs_projects");

                    b.HasIndex("AppId")
                        .HasDatabaseName("ix_cs_projects_app_id");

                    b.ToTable("cs_projects", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudAppUrl")
                        .HasColumnType("text")
                        .HasColumnName("cloud_app_url");

                    b.Property<string>("CloudContainerRevision")
                        .HasColumnType("text")
                        .HasColumnName("cloud_container_revision");

                    b.Property<long?>("CloudGitHubActionRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("cloud_git_hub_action_run_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CsProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("cs_project_id");

                    b.Property<string>("DockerContainerId")
                        .HasColumnType("text")
                        .HasColumnName("docker_container_id");

                    b.Property<string>("ImageTag")
                        .HasColumnType("text")
                        .HasColumnName("image_tag");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("CsProjectId")
                        .HasDatabaseName("ix_deployments_cs_project_id");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GitHubWorkflowCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<DateTimeOffset?>("FinalReconciledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("final_reconciled_at");

                    b.Property<string>("LastWorkflowStateFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_workflow_state_fingerprint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkflowAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_attempt");

                    b.Property<long>("WorkflowRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_git_hub_workflow_checkpoints");

                    b.HasIndex("DeploymentId", "WorkflowRunId", "WorkflowAttempt")
                        .IsUnique()
                        .HasDatabaseName("ix_git_hub_workflow_checkpoints_deployment_id_workflow_run_id_");

                    b.ToTable("git_hub_workflow_checkpoints", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GitHubWorkflowJobCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FinalArchiveContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("final_archive_content_hash");

                    b.Property<Guid>("GitHubWorkflowCheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("git_hub_workflow_checkpoint_id");

                    b.Property<bool>("IsLogFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_log_final");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("job_name");

                    b.Property<DateTimeOffset?>("LastLogCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_log_checked_at");

                    b.Property<string>("LastLogContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_log_content_hash");

                    b.Property<int>("LastLogLineCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_log_line_count");

                    b.Property<string>("LastLogPrefixHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_log_prefix_hash");

                    b.Property<string>("LastStateFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_state_fingerprint");

                    b.Property<int>("LogAvailability")
                        .HasColumnType("integer")
                        .HasColumnName("log_availability");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_git_hub_workflow_job_checkpoints");

                    b.HasIndex("GitHubWorkflowCheckpointId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_git_hub_workflow_job_checkpoints_git_hub_workflow_checkpoin");

                    b.ToTable("git_hub_workflow_job_checkpoints", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("user_type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LocalUser", b =>
                {
                    b.HasBaseType("Domain.Entities.User");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("email_verification_token");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("VerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_token_expiry");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator().HasValue("local");
                });

            modelBuilder.Entity("Domain.Entities.RemoteUser", b =>
                {
                    b.HasBaseType("Domain.Entities.User");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("AzureAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("azure_access_token");

                    b.Property<string>("AzureAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("azure_account_id");

                    b.Property<string>("AzureRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("azure_refresh_token");

                    b.Property<string>("AzureSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("azure_subscription_id");

                    b.Property<string>("AzureTenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("azure_tenant_id");

                    b.Property<DateTimeOffset?>("AzureTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("azure_token_expires_at");

                    b.Property<string>("GitHubAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("git_hub_access_token");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator().HasValue("github");
                });

            modelBuilder.Entity("Domain.Entities.Application", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.AzureContainerAppLogCheckpoint", b =>
                {
                    b.HasOne("Domain.Entities.Deployment", "Deployment")
                        .WithMany("AzureContainerAppLogCheckpoints")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_azure_container_app_log_checkpoints_deployments_deployment_");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Domain.Entities.Configuration", b =>
                {
                    b.HasOne("Domain.Entities.CsProject", "CsProject")
                        .WithOne("Configuration")
                        .HasForeignKey("Domain.Entities.Configuration", "CsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_configs_cs_projects_cs_project_id");

                    b.Navigation("CsProject");
                });

            modelBuilder.Entity("Domain.Entities.CsProject", b =>
                {
                    b.HasOne("Domain.Entities.Application", "Application")
                        .WithMany("CsProjects")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cs_projects_applications_app_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Domain.Entities.Deployment", b =>
                {
                    b.HasOne("Domain.Entities.CsProject", "CsProject")
                        .WithMany("Deployments")
                        .HasForeignKey("CsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_cs_projects_cs_project_id");

                    b.Navigation("CsProject");
                });

            modelBuilder.Entity("Domain.Entities.GitHubWorkflowCheckpoint", b =>
                {
                    b.HasOne("Domain.Entities.Deployment", "Deployment")
                        .WithMany("GitHubWorkflowCheckpoints")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_workflow_checkpoints_deployments_deployment_id");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Domain.Entities.GitHubWorkflowJobCheckpoint", b =>
                {
                    b.HasOne("Domain.Entities.GitHubWorkflowCheckpoint", "WorkflowCheckpoint")
                        .WithMany("JobCheckpoints")
                        .HasForeignKey("GitHubWorkflowCheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_workflow_job_checkpoints_git_hub_workflow_checkpoin");

                    b.Navigation("WorkflowCheckpoint");
                });

            modelBuilder.Entity("Domain.Entities.Application", b =>
                {
                    b.Navigation("CsProjects");
                });

            modelBuilder.Entity("Domain.Entities.CsProject", b =>
                {
                    b.Navigation("Configuration");

                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("Domain.Entities.Deployment", b =>
                {
                    b.Navigation("AzureContainerAppLogCheckpoints");

                    b.Navigation("GitHubWorkflowCheckpoints");
                });

            modelBuilder.Entity("Domain.Entities.GitHubWorkflowCheckpoint", b =>
                {
                    b.Navigation("JobCheckpoints");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
