using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddTerminalLogReplay : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE deployment_diagnostic_records ADD COLUMN order_id bigint;");
            migrationBuilder.Sql("""
                WITH numbered AS (
                    SELECT id, row_number() OVER (ORDER BY created_at, id) AS number
                    FROM deployment_diagnostic_records
                )
                UPDATE deployment_diagnostic_records AS record
                SET order_id = numbered.number
                FROM numbered WHERE record.id = numbered.id;
                """);
            migrationBuilder.Sql("""
                ALTER TABLE deployment_diagnostic_records ALTER COLUMN order_id SET NOT NULL;
                ALTER TABLE deployment_diagnostic_records ALTER COLUMN order_id
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT setval(pg_get_serial_sequence('deployment_diagnostic_records', 'order_id'),
                    COALESCE((SELECT max(order_id) FROM deployment_diagnostic_records), 0) + 1, false);
                """);

            migrationBuilder.AddColumn<string>(
                name: "terminal_channel",
                table: "deployment_diagnostic_records",
                type: "character varying(128)",
                maxLength: 128,
                nullable: true);
            migrationBuilder.Sql("""
                UPDATE deployment_diagnostic_records
                SET terminal_channel = 'github-actions'
                WHERE source = 'GitHubActions' AND deployment_id IS NOT NULL AND kind <> 'Metric';
                """);
            migrationBuilder.Sql("""
                UPDATE deployment_diagnostic_records
                SET terminal_channel = CASE
                    WHEN attributes_json::jsonb ->> 'source_table' LIKE 'ContainerAppConsoleLogs%'
                        THEN 'azure-web'
                    ELSE 'azure-system'
                END
                WHERE source = 'AzureContainerApps' AND deployment_id IS NOT NULL AND kind <> 'Metric';
                """);

            migrationBuilder.CreateIndex(
                name: "ix_deployment_diagnostic_records_order_id",
                table: "deployment_diagnostic_records",
                column: "order_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_deployment_diagnostic_records_project_id_deployment_id_orde",
                table: "deployment_diagnostic_records",
                columns: new[] { "project_id", "deployment_id", "order_id" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_deployment_diagnostic_records_order_id",
                table: "deployment_diagnostic_records");

            migrationBuilder.DropIndex(
                name: "ix_deployment_diagnostic_records_project_id_deployment_id_orde",
                table: "deployment_diagnostic_records");

            migrationBuilder.DropColumn(
                name: "order_id",
                table: "deployment_diagnostic_records");

            migrationBuilder.DropColumn(
                name: "terminal_channel",
                table: "deployment_diagnostic_records");
        }
    }
}
