// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AutoMateDbContext))]
    [Migration("20261004201350_AddAiAnalysisResultProvenance")]
    partial class AddAiAnalysisResultProvenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AiDeploymentAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CostCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cost_currency");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("EvidenceReferencesJson")
                        .HasColumnType("text")
                        .HasColumnName("evidence_references_json");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failure_code");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_version");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("RecommendedStepsJson")
                        .HasColumnType("text")
                        .HasColumnName("recommended_steps_json");

                    b.Property<string>("RequestedModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_model");

                    b.Property<int?>("ResultSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("result_schema_version");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer")
                        .HasColumnName("trigger");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ai_deployment_analyses");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_ai_deployment_analyses_expires_at");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_deployment_analyses_idempotency_key");

                    b.HasIndex("DeploymentId", "CreatedAt")
                        .HasDatabaseName("ix_ai_deployment_analyses_deployment_id_created_at");

                    b.ToTable("ai_deployment_analyses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AppType")
                        .HasColumnType("integer")
                        .HasColumnName("app_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ManagedTelemetryConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("managed_telemetry_consent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RuntimeDiagnosticsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("runtime_diagnostics_enabled");

                    b.Property<string>("SourcePathOrUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_path_or_url");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_applications_user_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AzureContainerAppLogCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<DateTimeOffset?>("LastSuccessfulQueryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_query_at");

                    b.Property<string>("LastTieBreaker")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_tie_breaker");

                    b.Property<DateTimeOffset?>("LastTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_timestamp");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_azure_container_app_log_checkpoints");

                    b.HasIndex("DeploymentId", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_azure_container_app_log_checkpoints_deployment_id_source");

                    b.ToTable("azure_container_app_log_checkpoints", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CloudDeploymentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("branch_name");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_name");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset?>("LaunchStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("launch_started_at");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phase");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RegistryServer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("registry_server");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("repository_id");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("repository_name");

                    b.Property<string>("RepositoryOwner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("repository_owner");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkflowFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workflow_file_name");

                    b.Property<long?>("WorkflowRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_cloud_deployment_runs");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_cloud_deployment_runs_project_id_created_at");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_cloud_deployment_runs_user_id_idempotency_key");

                    b.HasIndex("UserId", "LaunchStartedAt")
                        .HasDatabaseName("ix_cloud_deployment_runs_user_id_launch_started_at");

                    b.HasIndex("InstallationId", "Phase", "LeaseUntil")
                        .HasDatabaseName("ix_cloud_deployment_runs_installation_id_phase_lease_until");

                    b.HasIndex("InstallationId", "RepositoryId", "CommitSha")
                        .HasDatabaseName("ix_cloud_deployment_runs_installation_id_repository_id_commit_");

                    b.HasIndex("Phase", "NextAttemptAt", "CreatedAt")
                        .HasDatabaseName("ix_cloud_deployment_runs_phase_next_attempt_at_created_at");

                    b.HasIndex("UserId", "Phase", "LeaseUntil")
                        .HasDatabaseName("ix_cloud_deployment_runs_user_id_phase_lease_until");

                    b.HasIndex("RepositoryId", "BranchName", "EnvironmentName", "CreatedAt")
                        .HasDatabaseName("ix_cloud_deployment_runs_repository_id_branch_name_environment");

                    b.ToTable("cloud_deployment_runs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CloudInstallationBudget", b =>
                {
                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("PausedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_until");

                    b.Property<int>("ThrottleCount")
                        .HasColumnType("integer")
                        .HasColumnName("throttle_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InstallationId")
                        .HasName("pk_cloud_installation_budgets");

                    b.ToTable("cloud_installation_budgets", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CloudRunOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cloud_run_outbox");

                    b.HasIndex("DispatchedAt")
                        .HasDatabaseName("ix_cloud_run_outbox_dispatched_at");

                    b.HasIndex("RunId")
                        .IsUnique()
                        .HasDatabaseName("ix_cloud_run_outbox_run_id");

                    b.ToTable("cloud_run_outbox", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CloudWebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("conclusion");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("delivery_id");

                    b.Property<string>("HeadBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("head_branch");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("head_sha");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("repository_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkflowAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_attempt");

                    b.Property<string>("WorkflowPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("workflow_path");

                    b.Property<long>("WorkflowRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_cloud_webhook_deliveries");

                    b.HasIndex("DeliveryId")
                        .IsUnique()
                        .HasDatabaseName("ix_cloud_webhook_deliveries_delivery_id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("ix_cloud_webhook_deliveries_processed_at_created_at");

                    b.ToTable("cloud_webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AiDiagnosticEgressConsented")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_diagnostic_egress_consented");

                    b.Property<string>("CloudAzureRegion")
                        .HasColumnType("text")
                        .HasColumnName("cloud_azure_region");

                    b.Property<string>("CloudContainerAppName")
                        .HasColumnType("text")
                        .HasColumnName("cloud_container_app_name");

                    b.Property<string>("CloudRegistryName")
                        .HasColumnType("text")
                        .HasColumnName("cloud_registry_name");

                    b.Property<string>("CloudResourceGroupName")
                        .HasColumnType("text")
                        .HasColumnName("cloud_resource_group_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CsProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("cs_project_id");

                    b.Property<string>("DotNetVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dot_net_version");

                    b.Property<string>("EnvironmentVariablesJson")
                        .HasColumnType("text")
                        .HasColumnName("environment_variables_json");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<int?>("LocalExposedPort")
                        .HasColumnType("integer")
                        .HasColumnName("local_exposed_port");

                    b.Property<bool>("RequiresDb")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_db");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_configs");

                    b.HasIndex("CsProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_configs_cs_project_id");

                    b.ToTable("app_configs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CsProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsWebProject")
                        .HasColumnType("boolean")
                        .HasColumnName("is_web_project");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cs_projects");

                    b.HasIndex("AppId")
                        .HasDatabaseName("ix_cs_projects_app_id");

                    b.ToTable("cs_projects", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudAppUrl")
                        .HasColumnType("text")
                        .HasColumnName("cloud_app_url");

                    b.Property<string>("CloudContainerAppName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cloud_container_app_name");

                    b.Property<string>("CloudContainerRevision")
                        .HasColumnType("text")
                        .HasColumnName("cloud_container_revision");

                    b.Property<long?>("CloudGitHubActionRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("cloud_git_hub_action_run_id");

                    b.Property<string>("CloudResourceId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("cloud_resource_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CsProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("cs_project_id");

                    b.Property<string>("DockerContainerId")
                        .HasColumnType("text")
                        .HasColumnName("docker_container_id");

                    b.Property<string>("ImageTag")
                        .HasColumnType("text")
                        .HasColumnName("image_tag");

                    b.Property<Guid?>("RuntimeCollectorLeaseOwner")
                        .HasColumnType("uuid")
                        .HasColumnName("runtime_collector_lease_owner");

                    b.Property<DateTimeOffset?>("RuntimeCollectorLeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("runtime_collector_lease_until");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("CsProjectId")
                        .HasDatabaseName("ix_deployments_cs_project_id");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeploymentAnalysisWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deployment_analysis_work_items");

                    b.HasIndex("AnalysisId")
                        .IsUnique()
                        .HasDatabaseName("ix_deployment_analysis_work_items_analysis_id");

                    b.HasIndex("CompletedAt", "ClaimedAt")
                        .HasDatabaseName("ix_deployment_analysis_work_items_completed_at_claimed_at");

                    b.ToTable("deployment_analysis_work_items", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeploymentDailyTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("container");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DayUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("day_utc");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<bool>("Incomplete")
                        .HasColumnType("boolean")
                        .HasColumnName("incomplete");

                    b.Property<double?>("Maximum")
                        .HasColumnType("double precision")
                        .HasColumnName("maximum");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("metric");

                    b.Property<double?>("Minimum")
                        .HasColumnType("double precision")
                        .HasColumnName("minimum");

                    b.Property<long>("ObservedErrors")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_errors");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("SampleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_count");

                    b.Property<double>("Sum")
                        .HasColumnType("double precision")
                        .HasColumnName("sum");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_deployment_daily_telemetry");

                    b.HasIndex("UserId", "ProjectId", "DayUtc")
                        .HasDatabaseName("ix_deployment_daily_telemetry_user_id_project_id_day_utc");

                    b.HasIndex("DeploymentId", "DayUtc", "Container", "Metric")
                        .IsUnique()
                        .HasDatabaseName("ix_deployment_daily_telemetry_deployment_id_day_utc_container_");

                    b.ToTable("deployment_daily_telemetry", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeploymentDiagnosticRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("text")
                        .HasColumnName("attributes_json");

                    b.Property<DateTimeOffset?>("BufferExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("buffer_expires_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cursor")
                        .HasColumnType("text")
                        .HasColumnName("cursor");

                    b.Property<bool>("DeliveryAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("delivery_accepted");

                    b.Property<int>("DeliveryBytes")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_bytes");

                    b.Property<string>("DeliveryJson")
                        .HasColumnType("text")
                        .HasColumnName("delivery_json");

                    b.Property<Guid?>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MetricSamplesJson")
                        .HasColumnType("text")
                        .HasColumnName("metric_samples_json");

                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderId"));

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("SourceIdentityJson")
                        .HasColumnType("text")
                        .HasColumnName("source_identity_json");

                    b.Property<string>("SpanId")
                        .HasColumnType("text")
                        .HasColumnName("span_id");

                    b.Property<DateTimeOffset?>("StoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stored_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TerminalChannel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("terminal_channel");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deployment_diagnostic_records");

                    b.HasIndex("BufferExpiresAt")
                        .HasDatabaseName("ix_deployment_diagnostic_records_buffer_expires_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_deployment_diagnostic_records_expires_at");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_deployment_diagnostic_records_order_id");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_deployment_diagnostic_records_tenant_id_order_id");

                    b.HasIndex("DeploymentId", "TimestampUtc", "Sequence")
                        .HasDatabaseName("ix_deployment_diagnostic_records_deployment_id_timestamp_utc_s");

                    b.HasIndex("ProjectId", "DeploymentId", "OrderId")
                        .HasDatabaseName("ix_deployment_diagnostic_records_project_id_deployment_id_orde");

                    b.ToTable("deployment_diagnostic_records", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GitHubWorkflowCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<DateTimeOffset?>("FinalReconciledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("final_reconciled_at");

                    b.Property<string>("LastWorkflowStateFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_workflow_state_fingerprint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkflowAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_attempt");

                    b.Property<long>("WorkflowRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_git_hub_workflow_checkpoints");

                    b.HasIndex("DeploymentId", "WorkflowRunId", "WorkflowAttempt")
                        .IsUnique()
                        .HasDatabaseName("ix_git_hub_workflow_checkpoints_deployment_id_workflow_run_id_");

                    b.ToTable("git_hub_workflow_checkpoints", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GitHubWorkflowJobCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FinalArchiveContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("final_archive_content_hash");

                    b.Property<Guid>("GitHubWorkflowCheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("git_hub_workflow_checkpoint_id");

                    b.Property<bool>("IsLogFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_log_final");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("job_name");

                    b.Property<DateTimeOffset?>("LastLogCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_log_checked_at");

                    b.Property<string>("LastLogContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_log_content_hash");

                    b.Property<int>("LastLogLineCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_log_line_count");

                    b.Property<string>("LastLogPrefixHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_log_prefix_hash");

                    b.Property<string>("LastStateFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_state_fingerprint");

                    b.Property<int>("LogAvailability")
                        .HasColumnType("integer")
                        .HasColumnName("log_availability");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_git_hub_workflow_job_checkpoints");

                    b.HasIndex("GitHubWorkflowCheckpointId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_git_hub_workflow_job_checkpoints_git_hub_workflow_checkpoin");

                    b.ToTable("git_hub_workflow_job_checkpoints", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TelemetryTenantState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<long>("BufferedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("buffered_bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DroppedEvents")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_events");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<DateTimeOffset>("LastStoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_stored_at");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("MetricIdentitiesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_identities_json");

                    b.Property<long>("RateWindowBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("rate_window_bytes");

                    b.Property<DateTimeOffset>("RateWindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rate_window_start");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_telemetry_tenant_states");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("ix_telemetry_tenant_states_due_at");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_telemetry_tenant_states_tenant_id");

                    b.ToTable("telemetry_tenant_states", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("user_type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LocalUser", b =>
                {
                    b.HasBaseType("Domain.Entities.User");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("email_verification_token");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("VerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_token_expiry");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator().HasValue("local");
                });

            modelBuilder.Entity("Domain.Entities.RemoteUser", b =>
                {
                    b.HasBaseType("Domain.Entities.User");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("AzureAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("azure_access_token");

                    b.Property<string>("AzureAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("azure_account_id");

                    b.Property<string>("AzureRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("azure_refresh_token");

                    b.Property<string>("AzureSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("azure_subscription_id");

                    b.Property<string>("AzureTenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("azure_tenant_id");

                    b.Property<DateTimeOffset?>("AzureTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("azure_token_expires_at");

                    b.Property<string>("GitHubAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("git_hub_access_token");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator().HasValue("github");
                });

            modelBuilder.Entity("Domain.Entities.AiDeploymentAnalysis", b =>
                {
                    b.HasOne("Domain.Entities.Deployment", "Deployment")
                        .WithMany("AiAnalyses")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_deployment_analyses_deployments_deployment_id");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Domain.Entities.Application", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.AzureContainerAppLogCheckpoint", b =>
                {
                    b.HasOne("Domain.Entities.Deployment", "Deployment")
                        .WithMany("AzureContainerAppLogCheckpoints")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_azure_container_app_log_checkpoints_deployments_deployment_");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Domain.Entities.CloudDeploymentRun", b =>
                {
                    b.HasOne("Domain.Entities.Application", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cloud_deployment_runs_applications_project_id");

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cloud_deployment_runs_users_user_id");
                });

            modelBuilder.Entity("Domain.Entities.CloudRunOutbox", b =>
                {
                    b.HasOne("Domain.Entities.CloudDeploymentRun", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.CloudRunOutbox", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cloud_run_outbox_cloud_deployment_runs_run_id");
                });

            modelBuilder.Entity("Domain.Entities.Configuration", b =>
                {
                    b.HasOne("Domain.Entities.CsProject", "CsProject")
                        .WithOne("Configuration")
                        .HasForeignKey("Domain.Entities.Configuration", "CsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_configs_cs_projects_cs_project_id");

                    b.Navigation("CsProject");
                });

            modelBuilder.Entity("Domain.Entities.CsProject", b =>
                {
                    b.HasOne("Domain.Entities.Application", "Application")
                        .WithMany("CsProjects")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cs_projects_applications_app_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Domain.Entities.Deployment", b =>
                {
                    b.HasOne("Domain.Entities.CsProject", "CsProject")
                        .WithMany("Deployments")
                        .HasForeignKey("CsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_cs_projects_cs_project_id");

                    b.Navigation("CsProject");
                });

            modelBuilder.Entity("Domain.Entities.DeploymentAnalysisWorkItem", b =>
                {
                    b.HasOne("Domain.Entities.AiDeploymentAnalysis", "Analysis")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.DeploymentAnalysisWorkItem", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_analysis_work_items_ai_deployment_analyses_analy");

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Domain.Entities.DeploymentDailyTelemetry", b =>
                {
                    b.HasOne("Domain.Entities.Deployment", null)
                        .WithMany()
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_daily_telemetry_deployments_deployment_id");
                });

            modelBuilder.Entity("Domain.Entities.DeploymentDiagnosticRecord", b =>
                {
                    b.HasOne("Domain.Entities.Deployment", "Deployment")
                        .WithMany("DiagnosticRecords")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_deployment_diagnostic_records_deployments_deployment_id");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Domain.Entities.GitHubWorkflowCheckpoint", b =>
                {
                    b.HasOne("Domain.Entities.Deployment", "Deployment")
                        .WithMany("GitHubWorkflowCheckpoints")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_workflow_checkpoints_deployments_deployment_id");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Domain.Entities.GitHubWorkflowJobCheckpoint", b =>
                {
                    b.HasOne("Domain.Entities.GitHubWorkflowCheckpoint", "WorkflowCheckpoint")
                        .WithMany("JobCheckpoints")
                        .HasForeignKey("GitHubWorkflowCheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_workflow_job_checkpoints_git_hub_workflow_checkpoin");

                    b.Navigation("WorkflowCheckpoint");
                });

            modelBuilder.Entity("Domain.Entities.Application", b =>
                {
                    b.Navigation("CsProjects");
                });

            modelBuilder.Entity("Domain.Entities.CsProject", b =>
                {
                    b.Navigation("Configuration");

                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("Domain.Entities.Deployment", b =>
                {
                    b.Navigation("AiAnalyses");

                    b.Navigation("AzureContainerAppLogCheckpoints");

                    b.Navigation("DiagnosticRecords");

                    b.Navigation("GitHubWorkflowCheckpoints");
                });

            modelBuilder.Entity("Domain.Entities.GitHubWorkflowCheckpoint", b =>
                {
                    b.Navigation("JobCheckpoints");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
