using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Components;
using Services.Auth;

namespace Web.Components.Pages;

/// <summary>
///     The RegistryForm component is responsible for handling the registration process
///     for new users. It displays a form for user input, validates the input, and handles
///     the registration logic.
/// </summary>
public partial class RegistryForm : ComponentBase
{
    /// Navigation manager to handle URL navigation after registration.
    [Inject]
    private NavigationManager NavigationManager { get; set; } = null!;

    /// Authentication service for user registration and verification.
    [Inject]
    private IAuthService AuthService { get; set; } = null!;

    /// Logger for logging registration-related events.
    [Inject]
    private ILogger<RegistryForm> Logger { get; set; } = null!;


    /// <summary>
    ///     The model bound to the registration form. Auto-initialized to avoid null references.
    /// </summary>
    [SupplyParameterFromForm]
    public RegisterModel? Model { get; set; }


    /// An optional error message to display if the registration fails.
    private string? ErrorMessage { get; set; }

    /// Indicates whether the registration form is currently being submitted.
    private bool IsSubmitting { get; set; }


    /// <summary>
    ///     Initializes the component and ensures that the Model is not null to prevent issues with form binding.
    /// </summary>
    protected override void OnInitialized()
    {
        Model ??= new RegisterModel();
    }


    /// <summary>
    ///     Handles the registration process when the form is submitted and passes validation.
    ///     It calls the authentication service to register the user and sends a verification email.
    /// </summary>
    private async Task HandleRegistration()
    {
        if (Model is null || IsSubmitting) return;

        ErrorMessage = null;
        IsSubmitting = true;

        try
        {
            var success = await AuthService.RegisterAsync(
                Model.Username,
                Model.Email,
                Model.Password,
                GenerateVerificationLink);

            if (!success)
            {
                ErrorMessage = "This email address is already in use or the verification email could not be sent.";
                return;
            }

            NavigationManager.NavigateTo("/verify-email?checkemail=true");
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Registration failed unexpectedly for email {Email}.", Model.Email);
            ErrorMessage = "Registration failed unexpectedly. Please try again later.";
        }
        finally
        {
            IsSubmitting = false;
        }
    }


    /// <summary>
    ///     Generates the absolute URL required for the email verification process.
    /// </summary>
    /// <param name="token">The unique verification token generated by the service.</param>
    /// <returns>A formatted URL string containing the verification token.</returns>
    private string GenerateVerificationLink(string token)
    {
        var baseUri = NavigationManager.ToAbsoluteUri("/verify-email").ToString();

        return NavigationManager.GetUriWithQueryParameters(
            baseUri,
            new Dictionary<string, object?> { { "token", token } }
        );
    }


    /// <summary>
    ///     Model for user registration, containing validation attributes to ensure proper input.
    /// </summary>
    public class RegisterModel
    {
        /// <summary>
        ///     The user's email address used for login and email verification.
        /// </summary>
        [Required(ErrorMessage = "Email address required.")]
        [EmailAddress(ErrorMessage = "Invalid email format.")]
        public string Email { get; set; } = string.Empty;

        /// <summary>
        ///     The display username associated with the local account.
        /// </summary>
        [Required(ErrorMessage = "Username required.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Username must be between 3-50 characters.")]
        public string Username { get; set; } = string.Empty;

        /// <summary>
        ///     The password submitted for the new local account.
        /// </summary>
        [Required(ErrorMessage = "Password required.")]
        [MinLength(6, ErrorMessage = "Password must be at least 6 characters.")]
        public string Password { get; set; } = string.Empty;

        /// <summary>
        ///     The repeated password value used to confirm the submitted password.
        /// </summary>
        [Required(ErrorMessage = "Password confirmation required.")]
        [Compare(nameof(Password), ErrorMessage = "Passwords do not match.")]
        public string ConfirmPassword { get; set; } = string.Empty;
    }
}