using Core.Enums;

namespace Core.Entities;

/// <summary>
///     Represents a deployment of a project, including the
///     time it was deployed, its status, and any logs associated with the deployment.
/// </summary>
public class Deployment : BaseEntity
{
    /// <summary>
    ///     Gets or sets the unique identifier of the project associated with this deployment.
    /// </summary>
    public Guid CsProjectId { get; set; }

    /// <summary>
    ///     Gets or sets the current status of the deployment.
    /// </summary>
    public DeploymentStatus Status { get; set; }

    /// <summary>
    ///     Gets or sets the tag/name of the generated Docker image (e.g., "automate-mywebapi-local").
    /// </summary>
    public string? ImageTag { get; set; }

    /// <summary>
    ///     Gets or sets the unique ID generated by the Docker Engine for the running container.
    ///     This is strictly required to stop, start, or monitor the container.
    /// </summary>
    public string? DockerContainerId { get; set; }

    /// <summary>
    ///     Gets or sets a reference to the project associated with this deployment.
    /// </summary>
    public CsProject? CsProject { get; set; }
}