FROM mcr.microsoft.com/dotnet/sdk:{{ dotnet_version }} AS build
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY ["{{ project_name }}/{{ project_name }}.csproj", "{{ project_name }}/"]
RUN dotnet restore "{{ project_name }}/{{ project_name }}.csproj"

# Copy everything else and build
COPY . .
WORKDIR "/src/{{ project_name }}"
RUN dotnet build "{{ project_name }}.csproj" -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish "{{ project_name }}.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:{{ dotnet_version }} AS final
WORKDIR /app
EXPOSE {{ exposed_port }}
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "{{ project_name }}.dll"]