FROM mcr.microsoft.com/dotnet/sdk:{{ dotnet_version }} AS build
WORKDIR /src

# Copy the project files
{{ for project in projects }}
COPY ["{{ project.relative_path }}", "{{ project.folder }}/"]
{{ end }}

# Restore the main project
RUN dotnet restore "{{ main_project_relative_path }}"

# Copy the remaining files
COPY . .

# Build the main project
WORKDIR "/src/{{ main_project_folder }}"
RUN dotnet build "{{ project_name }}.csproj" -c Release -o /app/build

# Publish the main project
FROM build AS publish
RUN dotnet publish "{{ project_name }}.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Create the final image
FROM mcr.microsoft.com/dotnet/aspnet:{{ dotnet_version }} AS final
WORKDIR /app
EXPOSE {{ exposed_port }}
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "{{ project_name }}.dll"]