using Domain.Enums;

namespace Domain.Entities;

/// <summary>
///     Represents a deployment of a project, including the
///     time it was deployed, its status, and any logs associated with the deployment.
/// </summary>
public class Deployment : BaseEntity
{
    /// <summary>Last owner-saved assessment choices; never credentials or diagnostics.</summary>
    public string? AiAssessmentPreferencesJson { get; set; }

    /// <summary>Serialized immutable non-secret configuration; null for legacy deployments.</summary>
    public string? ConfigurationSnapshotJson { get; set; }

    /// <summary>Completion outcome retained after runtime status changes.</summary>
    public DeploymentOutcome Outcome { get; set; }

    /// <summary>Time a deployment completed preparation successfully or failed.</summary>
    public DateTimeOffset? FinishedAt { get; set; }

    /// <summary>Resolved local host port; independent of later configuration edits.</summary>
    public int? ResolvedHostPort { get; set; }

    /// <summary>
    ///     Gets or sets the unique identifier of the project associated with this deployment.
    /// </summary>
    public Guid CsProjectId { get; set; }

    /// <summary>
    ///     Gets or sets a reference to the project associated with this deployment.
    /// </summary>
    public CsProject? CsProject { get; set; }

    /// <summary>
    ///     Gets or sets the current status of the deployment.
    /// </summary>
    public DeploymentStatus Status { get; set; }

    /// <summary>
    ///     Gets or sets the tag/name of the generated Docker image (e.g., "automate-mywebapi-local").
    /// </summary>
    public string? ImageTag { get; set; }


    /// <summary>
    ///     Gets or sets the unique ID generated by the Docker Engine for the running container.
    ///     This is strictly required to stop, start, or monitor the container.
    /// </summary>
    public string? DockerContainerId { get; set; }


    /// <summary>
    ///     Gets or sets the unique ID of the GitHub Actions workflow run associated with this deployment.
    /// </summary>
    public long? CloudGitHubActionRunId { get; set; }

    /// <summary>
    ///     Gets or sets the URL of the deployed application in the cloud.
    /// </summary>
    public string? CloudAppUrl { get; set; }

    /// <summary>
    ///     Gets or sets the revision of the deployed application in the cloud.
    /// </summary>
    public string? CloudContainerRevision { get; set; }

    /// <summary>Non-secret provider identity used to recover cloud collectors after restart.</summary>
    public string? CloudResourceId { get; set; }

    public string? CloudContainerAppName { get; set; }
    public Guid? RuntimeCollectorLeaseOwner { get; set; }
    public DateTimeOffset? RuntimeCollectorLeaseUntil { get; set; }

    /// <summary>Durable non-sensitive checkpoints for GitHub Actions diagnostic streaming.</summary>
    public ICollection<GitHubWorkflowCheckpoint> GitHubWorkflowCheckpoints { get; set; } = [];

    /// <summary>Durable non-sensitive cursors for Azure Container Apps runtime log streaming.</summary>
    public ICollection<AzureContainerAppLogCheckpoint> AzureContainerAppLogCheckpoints { get; set; } = [];

    public ICollection<AiDeploymentAnalysis> AiAnalyses { get; set; } = [];
    public ICollection<DeploymentDiagnosticRecord> DiagnosticRecords { get; set; } = [];
}